CREATE TABLE IF NOT EXISTS ACTOR (
    act_id INTEGER NOT NULL AUTO_INCREMENT,
    act_fname CHAR(20) NOT NULL,
    act_lname CHAR(20) NOT NULL,
    act_gender ENUM('M', 'F') NULL,
    CONSTRAINT ACTOR_PK PRIMARY KEY (act_id)
);

CREATE TABLE IF NOT EXISTS MOVIE (
    movie_id INTEGER NOT NULL AUTO_INCREMENT,
    mov_title CHAR(45) NOT NULL,
    mov_year INTEGER NOT NULL,
    mov_time INTEGER NOT NULL,
    mov_lang CHAR(45) NOT NULL,
    mov_dt_rel DATE NULL,
    mov_rel_country CHAR(45) NOT NULL,
    CONSTRAINT MOVIE_PK PRIMARY KEY (movie_id)
);

CREATE TABLE IF NOT EXISTS DIRECTOR (
    dir_id INTEGER NOT NULL AUTO_INCREMENT,
    dir_fname CHAR(20) NOT NULL,
    dir_lname CHAR(20) NOT NULL,
    CONSTRAINT DIRECTOR_PK PRIMARY KEY (dir_id)
);

CREATE TABLE IF NOT EXISTS GENRES (
    gen_id INTEGER NOT NULL AUTO_INCREMENT,
    gen_title CHAR(20) NOT NULL,
    CONSTRAINT GENRES_PK PRIMARY KEY (gen_id)
);

CREATE TABLE IF NOT EXISTS REVIEWER (
    rev_id INTEGER NOT NULL AUTO_INCREMENT,
    rev_name CHAR(30) NULL,
    CONSTRAINT REVIEWER_PK PRIMARY KEY (rev_id)
);

CREATE TABLE IF NOT EXISTS MOVIE_CAST (
    act_id INTEGER NOT NULL,
    movie_id INTEGER NOT NULL,
    role CHAR(50)  NULL,
    CONSTRAINT MOVIE_CAST_PK PRIMARY KEY (act_id, movie_id),
    CONSTRAINT ACTOR_FK FOREIGN KEY (act_id)
        REFERENCES ACTOR (act_id),
    CONSTRAINT MOVIE_FK FOREIGN KEY (movie_id)
        REFERENCES MOVIE (movie_id)
);

CREATE TABLE IF NOT EXISTS MOVIE_DIRECTION (
    dir_id INTEGER NOT NULL,
    movie_id INTEGER NOT NULL,
    CONSTRAINT MOVIE_DIRECTION_PK PRIMARY KEY ( dir_id,movie_id ),
    CONSTRAINT DIRECTOR_FK FOREIGN KEY (dir_id)
        REFERENCES DIRECTOR  (dir_id),
    CONSTRAINT  MOVIE1_FK FOREIGN KEY (movie_id)
        REFERENCES MOVIE (movie_id)
);

CREATE TABLE IF NOT EXISTS MOVIE_GENRES (
    movie_id INTEGER NOT NULL,
    gen_id INTEGER NOT NULL,
    CONSTRAINT MOVIE_GENRES_PK PRIMARY KEY (movie_id , gen_id),
    CONSTRAINT MOVIE2_FK FOREIGN KEY (movie_id)
        REFERENCES MOVIE (movie_id),
    CONSTRAINT GENRES_FK FOREIGN KEY (gen_id)
        REFERENCES GENRES (gen_id)
);

CREATE TABLE IF NOT EXISTS RATINGS (
    movie_id INTEGER  NOT NULL,
    rev_id INTEGER NOT NULL,
    rev_stars INTEGER  NULL,
    num_o_ratings INTEGER NULL,
    CONSTRAINT RATINGS_PK PRIMARY KEY (movie_id , rev_id),
    CONSTRAINT MOVIE3_FK FOREIGN KEY (movie_id)
        REFERENCES MOVIE (movie_id),
    CONSTRAINT REVIEWER_FK FOREIGN KEY (rev_id)
        REFERENCES REVIEWER (rev_id)
);

